name: betclic-hollandais

type: nodejs:18

disk: 512
resources:
    base_memory: 1800

mounts:
  'logs':
    source: local
    source_path: logs

dependencies:
    nodejs:
        sharp: "*"

web:
    commands:
        start: "npm start"
    locations:
        /ws:
            passthru: true
