"https://{default}/":
    type: upstream
    upstream: "betclic-hollandais:http"
"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
"https://{default}/ws":
    type: upstream
    upstream: "betclic-hollandais:http"
    cache:
        enabled: false